[package]
name = "maths_lib"
version = "0.1.0"
edition = "2021"
authors = ["Keith Boehler <keith.boehler01@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
